apiVersion: apps/v1
kind: Deployment
metadata:
  name: mpi-operator
spec:
  template:
    spec:
      containers:
        - name: mpi-operator
          args:
            - -alsologtostderr
            - --lock-namespace
            - kubeflow
            - mpioperator/kubectl-delivery:lates
