apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: daskhub
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:Hardvor7/argoflow.git
    targetRevision: HEAD
    path: distribution/daskhub
  destination:
    server: https://kubernetes.default.svc
    namespace: daskhub
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
