apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: monitoring-ingressgateway-certs
  namespace: istio-system
spec:
  secretName: monitoring-ingressgateway-certs
  issuerRef:
    name: gateways-issuer
    kind: ClusterIssuer
  dnsNames:
    - grafana.51.222.45.24.nip.io
    - kiali.51.222.45.24.nip.io
    - kubecost.51.222.45.24.nip.io
