kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
    data: null
  encryptedData:
    admin-password: AgC/EFtRzHCTPWVtdfEBSk7SbJlbcJHZS9zjWr9OJ8rOJFLIDHRcXlzAzG6uHYH3fcdPBwyyq4UAn4jntGheVQYmFi7KF35oncAgGDgIepzqO7skQoZSWegvHJ01Mxi4cY5GE/bD7Shoe+/Z4C8yhgdJwrdRb/ulZVLcQlj6g3417HyzREMPflG08xMSVkkq8/3p21jtOUgRdsaa5qrJALx9BC1UOrk/617xAKOMM84Zx1nnPOAAmhbIxAfhJJ/F7P1ogTzMuIOD/f4hGtxHW7C1u0K3EU0SOpT6r1ecf+X/6QDidBYV+ycmth064cyctB+NdnCm3CQ3Agiiiy9uy6/atQ2cu0reOLhatYHPFVUSabeYhlswyQc0+3wSf0SwYgsUETAPs2ns4TKkXxQRRfM7q1olDao8X2d8XqwfBAo9VzfwnVG064vmvIObAF5MDrdxfWbKxAUhLe23s0vEk3Jv38LQjB55iO8tmCgYrV9a3765ytkODWDjYOQPb7MSUAJdS8HMGHb0vETJTUTNjy6tJyuamxKKmddIyc48/cdSUA+Xe0gnPCxaVkgAO6rS49jpcuU2ool9OcBsjHywKglMSA7CVa3FgsA74rlCesTZ7CV4AYRnFM+bv7Xg+oypj49DmxTCZ1GC/0URjYiusKLPWCFt+0VAiAnI7VsJf+oX8yaIMP627XrbC4yN04sUsn/ksI+LffA=
    admin-user: AgCWEv1po7EnRCbAYwo2+YiqKjPCuwpwq/cVz5wZzeXorF4QQiwgUsmewislTXJDaNnMDJwV12ss9PzZWX8XLgWoEF0Qvr74lAFfSsiXWeWVmPnIsSgRMZTXRq9u6QIyoG8RO6rDR+igKm2BB+obAtbpFyo32xAznC00go8j8yLAW+0NxHE2Fv6syHx2rihpJdykf4gBw4Cx3ogoKUFmFjit8oZzV3wzHKq+ZS7rfm8RGzR8pw5Ki0Wxdt8ACNUbJnhqBTI+mOSgww8EfS3kc57rfNH7Y0+dCmwDXgZBfOCLUq0LB0gIHniUMm+8f6YuhkBe3AqsJa+a0HwvxzMZ5mq6PGnbfROlASSNkfcPoznTUUOuXptHMf8D6+i/oRYfp/IvBOL7V/8tuwzxJenbyrn5ka6mekpT9IDVWSZjT17nwTR33z8WFnvc5w9yJz14QidcKxuqeiw++qD92l5O9syV8YnvK2Ccjs7oOpTwK3K0JtKK9OsR83pnI4AbuqC99gFGpDQfaUfbXtHiiQKAvDkG4RZLlR6P7TjGlhyzOgAfoAzhuHec+pba8EUTDDeESQiNFvJkK5DrGAsGosOsEQzLVdP9Rb5GQh1FIdL3VYZU72pvVEYOEMvtl7D5LJ1nHPzGRrGojZxZASJJPZX2RNoJJhaIzhbt5LuB6vsM1M4/aL8RxgiLUl46ZrZ2Zba87VqES+JPew==
